### ISSUE TITLE
Button with dismiss behavior do not close in app message on some Android devices.

### ISSUE THREAD

**Issue by 1mavic** [customerio/customerio-flutter#141]
Hello!

flutter 3.22.2
customer_io: 1.3.1
 
 **Problem**
 When user taps on dismiss button in in app message frame, some android devices do not close it. Or when i call 
 `  CustomerIO.messagingInApp().dismissMessage();`

**Stack trace**
 `PlatformException: PlatformException(dismissMessage, Unsupported value: 'kotlin.Unit' of type 'class Kd.G', java.lang.IllegalArgumentException: Unsupported value: 'kotlin.Unit' of type 'class Kd.G'
	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:439)
	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:12)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:11)
	at Ta.a.a(CustomerIOExtensions.kt:36)
	at Ua.a.onMethodCall(CustomerIOInAppMessaging.kt:23)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:18)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:19)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(DartMessenger.java:36)
	at io.flutter.embedding.engine.dart.DartMessenger.a(DartMessenger.java:1)
	at io.flutter.embedding.engine.dart.a.run(R8$$SyntheticClass:13)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:222)
	at android.os.Looper.loop(Looper.java:314)
	at android.app.ActivityThread.main(ActivityThread.java:8602)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:565)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
, null)`

**Comment by mrehan27** [comment]
Thanks @1mavic for sharing this. Sorry for the inconvenience this may have caused. The logs are really helpful and helped us identify the issue. We'll work on it and roll out the fix soon.

Appreciate your patience. Have a great day.
