### ISSUE TITLE
Fatal Exception: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by andrespaez90** [customerio/customerio-flutter#37]
Has anyone else experienced this error while using this library?

Version
`customer_io: ^1.0.0-beta.1`

Stacktrace

`Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:7896)
       at libcore.io.IoBridge.open(IoBridge.java:482)
       at java.io.FileInputStream.<init>(FileInputStream.java:159)
       at kotlin.io.FilesKt__FileReadWriteKt.readText(FilesKt__FileReadWrite.kt:125)
       at kotlin.io.FilesKt__FileReadWriteKt.readText$default(FilesKt__FileReadWrite.kt:125)
       at io.customer.sdk.data.store.FileStorage.get(FileStorage.java:62)
       at io.customer.sdk.queue.QueueStorageImpl.get(QueueStorageImpl.java:103)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks(QueueRunRequestImpl.java:37)
       at io.customer.sdk.queue.QueueRunRequestImpl.goToNextTask(QueueRunRequestImpl.java:84)
       at io.customer.sdk.queue.QueueRunRequestImpl.runTasks(QueueRunRequestImpl.java:57)
       at io.customer.sdk.queue.QueueRunRequestImpl.access$runTasks(QueueRunRequestImpl.java:12)
       at io.customer.sdk.queue.QueueRunRequestImpl$runTasks$1.invokeSuspend(QueueRunRequestImpl.java:13)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.java:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:664)`

**Comment by Shahroz16** [comment]
Hey, @andrespaez90 thank you for writing in, can you please try the latest stable version? This was fixed some time ago.

**Comment by levibostian** [comment]
Closing issue as I am assuming that the latest version no longer has this issue. 

@andrespaez90, re-open and send more details if you are still experiencing this issue.
